philomena-dev/philomena

lib/philomena_web/views/api/json/dnp_view.ex
lib/philomena_web/views/api/json/tag_view.ex

---
Adds full (what's visible through the web interface) DNP info to `/tags/:id` endpoint.
Expanded layout to make it easier to parse visually, and `mix format` on that.
Was requested on [`derpibooru`](https://github.com/derpibooru/philomena/issues/205) git.

Adds full DNP info to tags

---

lib/philomena/users/ability.ex

BoR behavior. Probably just an oversight since they can already undelete images.

Allows assistants to update tags on deleted images

---

lib/philomena/users/ability.ex

Mostly just allows deletion and editing gallery settings if the need arises. Not enough reason to add deleting/adding images at this time since it requires a lot of extra work to add for basically no gain.

Allow mods to manage galleries (somewhat)

---

docker/app/Dockerfile
docker/app/purge-cache
lib/philomena/images.ex
lib/philomena/images/hider.ex
lib/philomena/images/thumbnailer.ex
lib/philomena/workers/image_purge_worker.ex
lib/philomena_web/controllers/image/repair_controller.ex

Deployment instructions for non-Docker setups:
Create `/usr/local/bin/purge-cache` as an executable bash script. Replace its contents with custom logic if desired. An example is provided in the repository.
```bash
#!/bin/bash
#
#
body="$1"
api_token=
zone_id=
```

Cache purging callbacks

---

index/all.mk
index/filters.mk
lib/mix/tasks/reindex_all.ex
lib/philomena/elasticsearch.ex
lib/philomena/filters.ex
lib/philomena/filters/elasticsearch_index.ex
lib/philomena/filters/query.ex
lib/philomena/tags.ex
lib/philomena/users.ex
lib/philomena/workers/index_worker.ex
lib/philomena_web/controllers/api/json/search/filter_controller.ex
lib/philomena_web/controllers/filter_controller.ex
lib/philomena_web/router.ex
lib/philomena_web/templates/filter/index.html.slime
priv/repo/seeds.exs

---
Restores public filter search functionality from booru-on-rails. Ready to merge.
1. I'm not sure on how ElasticSearch migrations are done. Is reindex triggered manually? Should I add "Reindex All Filters" button?
2. Some filter fields are not visible to the user, so I'm not sure if it should be included in search. `created_at` field is not visible to both UI and API (I included it for now). `user_count` is not visible to UI, but visible on API (I did not include it yet). If `user_count` is safe to include, then it would be nice to sort by this field so that …

Public filter search

---

lib/philomena/comments.ex
lib/philomena/images.ex
lib/philomena/posts.ex
lib/philomena/topics.ex
lib/philomena/users.ex
lib/philomena/users/user.ex
lib/philomena_web/comment_loader.ex
lib/philomena_web/controllers/activity_controller.ex
lib/philomena_web/controllers/conversation_controller.ex
lib/philomena_web/controllers/filter/clear_recent.ex
lib/philomena_web/controllers/image_controller.ex
lib/philomena_web/router.ex
lib/philomena_web/templates/activity/index.html.slime
lib/philomena_web/templates/filter/index.html.slime
lib/philomena_web/templates/setting/edit.html.slime

---
Restores some of the missing booru-on-rails user options in Philomena.
- Notification tab is back
- Subscribe on Reply
- Subscribe on Upload
- Subscribe on New Threads
- Comments tab is back
- Show latest comment page
- Newest messages first
- Some options are moved from Display tab to here (Newest comments first, Comments per page)
- Display tab options
- Show sidebar and watched images
- "Clear recent filter list" checkbox option is implemented as a button in Filters page instead

User settings

---

lib/philomena_web/templates/gallery/index.html.slime

Dunno if it's in the right spot or whatever, and the 'Create Gallery' page isn't really helpful if you don't already know what image to use as a cover, but at least this gets their foot in the door.
---
I copied bits of code into a different place and trimmed them down until it made a passable "Create Gallery" button.  :P  Let me know if it should look different or be in a different place or anything.

Added 'Create Gallery' button to Galleries page.

---

lib/philomena_web/templates/image/favorite/index.html.slime

---
Sort favoriter/upvoter/downvoter/hider usernames case-insensitively, because it makes more sense logically (in my opinion).

Sort image favoriters' names case-insensitively

---

assets/css/common/_forms.scss

---
Due to the way the caret is rendered on the `select` box using a `background` property, the background color is reset to default on `option`s when the `select` box loses its `:hover` state. This is primarily noticeable on the dark theme. Although I'm not sure what the best fix for this is, the simplest solution is to just override the background color on `option` tags that are children of non-`:hover` `select` boxes.
This appears to be a bug in Chromium. Loading derpibooru.org in Firefox does not exhibit the same issue.
I have no idea what I'm doing with CSS. 🤔 …

Fix background color being reset on select options in Chrome

---

assets/css/common/_forms.scss
assets/css/common/_header.scss

---
In #159, I attempted to fix the dropdown background color in Chrome. Unfortunately, this had the side effect of breaking the background color of `select` boxes in the header, which was especially notable on light theme. This PR addresses this issue, and makes it so the active `select` box has its `option`s highlighted. Not 100% sure on the latter change, but it's easy to remove if it's undesired.
**Hovered:**
**Unhovered:**

Fix select background color in header, re-add hover color

---

lib/philomena_web/templates/profile/_statistics.html.slime

---
Currently, the user statistics is hardcoded to display only stats from the last 90 days. This isn't clear from the display. We can easily fit this content in the existing chart header.

Add the time range for the user statistics page

---

native/philomena/Cargo.lock

This updates comrak to 0.18.0 with philomena changes ported forward.
~~Note: we might also want to merge the changes from [here](https://github.com/philomena-dev/comrak/commits/c7821424efee8e104f96b3dbe71a468a5f939851) to help resolve some issues with hidden links?~~ Applied.

Update comrak to 0.18.0 (philomena fork)

---

lib/philomena/users/ability.ex
lib/philomena_web/controllers/image/tag_change_controller.ex
lib/philomena_web/router.ex
lib/philomena_web/templates/tag_change/index.html.slime

---
This used to be a thing in Booru on Rails but wasn't added to Philomena for some reason.

feat: add ability for staff to delete tag changes from tag change history

---

assets/js/upload.js

---
`js-image-source` is a div that wraps the input and the delete button. actual input is `js-source-url`

Fix setting source url in uploader after fetch

---

lib/philomena/images.ex
lib/philomena_web/plugs/admin_counters_plug.ex

---
Don't display approval queue shortcut (and the count of pending images) if the current user doesn't have permission to view  the approval queue.
This was bugging me. :)

Hide Queue staff link if user can't approve images

---

lib/philomena/workers/tag_change_revert_worker.ex
lib/philomena_web/controllers/tag_change/full_revert_controller.ex
lib/philomena_web/templates/fingerprint_profile/show.html.slime
lib/philomena_web/templates/ip_profile/show.html.slime

Adds UI to something I've been forced to do from console many times - to undo tag changes with batch size of 1 (so, going over each one of them individually), because batch size 100 is prone to fail under certain conditions (which occur frequently in practice), such as users fixing the tags before the mass reverter executes, or if the tag vandal changes them up again afterwards. Appropriate warning included to make sure people are aware that this is FUCKING SLOW.

UI to revert tag changes one-by-one

---

lib/philomena_web/templates/registration/edit.html.slime
lib/philomena_web/templates/setting/edit.html.slime

---
Having the API key show in plain sight in the account page is bad practice, there would be risks of people accidentally leaking their API keys because they went to the account page to check something but showing the API key to the public in the process in the case they were sharing their screens or streaming  on twitch.
Currently the way i am doing this behaviour is super scuffed, having the box be treated as an image filter is super wrong but its the only way i could think of. Same goes for overriding the initial pass of actions possible to the element which were …

Make API key & RSS feed url only show when clicked

---

lib/philomena/galleries.ex

---
Galleries currently have only one instance of Notification where they are the actor and child actor is nil. Not having a child actor causes that notification to have the same created_at and updated_at fields because child actor is the only thing that ever changes in a Notification. The issue is that notifications page uses notifcation.updated_at timestamp, so currently it displays when the first image was added to a gallery which could be years ago. This PR resolves it by making child actor the added image which forces updated_at to update.

Fix gallery notifications timestamps

---

assets/js/autocomplete.js
lib/philomena_web/controllers/autocomplete/tag_controller.ex

---
Local autocompleter currently takes top 50k tags (the cutoff is ~34 images right now). It'd be useful to have autocomplete for tags without that many images, e.g. for artists and OCs. This PR adds it by making autocomplete fallback to fetch if instant returns no results. This approach avoids adding additional 233k tags (`images.gt:0, images.lt:34, (artist:* || oc:*)`) to the precompiled binary. This PR also makes the fetch autocomplete return all tags with 1+ images instead of 4+.
Also see https://discord.com/channels/430829008402251796/438029140659142657/117546082 …

Autocomplete fallback

---

lib/philomena_web/views/image_view.ex

feat: more icons for source urls

---

lib/philomena/images/image.ex

width/height can be nil here, first case doesn't match but nil is indeed bigger than 32767, so the incorrect error message will be displayed
---

fix: misleading error if image is corrupted

---

assets/js/__tests__/ujs.spec.ts
assets/js/ujs.ts

This moves all of the ujs events convenience library into TypeScript. There should be no substantial changes to the logic here, but two bugs were discovered during testing and fixed:
1. Incorrect use of `target` where `input` was intended.
```js
$$('[disabled][data-disable-with][data-enable-with]', target).forEach(input => {
// ...
input.innerHTML = target.dataset.enableWith;
//                ^^^^^^ input
}
```
2. HTMLFormElement's method property is restricted, so the final 'POST' case is unreachable here:
```js
method: (target.dataset.method || target.method || 'POST').toUpperCase(),
```
This has 100% test coverage in unit tests and has also been manually integration tested.

ujs: migrate to TypeScript

---

assets/js/__tests__/timeago.spec.ts
assets/js/comment.js
assets/js/timeago.ts
assets/test/jest-setup.ts
assets/types/booru-object.d.ts

This moves all of the pretty timestamp conversion logic into TypeScript. There should be no effective changes to the logic here. Two uses of timeAgo outside the file were converted to import the function directly instead of using the version on window.booru - the version attached to window.booru is preserved for userscript compatibility only.
This has 100% test coverage in unit tests and has also been manually integration tested.

timeago: migrate to TypeScript

---

config/runtime.exs
lib/philomena_web/plugs/content_security_policy_plug.ex

"Fixes" https://github.com/philomena-dev/philomena/issues/235
There isn't a way to tell whether Plug.Debugger has rendered something, so just delete the CSP unconditionally on 500 responses in development/test mode. No change for prod mode.

Relax CSP on development error pages

---

assets/js/utils/__tests__/dom.spec.ts
assets/js/utils/__tests__/draggable.spec.ts
assets/js/utils/__tests__/image.spec.ts
assets/package-lock.json
assets/package.json
assets/test/vitest-setup.ts

---
Follow-up for #243 which pins chai at the latest major version at the time of writing and restores the previously used `@testing-library/jest-dom` for DOM assertions instead of the `chai-dom` library which does not appear to be compatible with the latest major `chai` version.

Eliminate chai-dom and restore @testing-library/jest-dom

---

lib/philomena_web/markdown_renderer.ex
lib/philomena_web/templates/admin/dnp_entry/index.html.slime
lib/philomena_web/templates/admin/mod_note/_table.html.slime
lib/philomena_web/templates/admin/report/show.html.slime
lib/philomena_web/templates/comment/_comment.html.slime
lib/philomena_web/templates/comment/_comment_with_image.html.slime
lib/philomena_web/templates/dnp_entry/index.html.slime
lib/philomena_web/templates/dnp_entry/show.html.slime
lib/philomena_web/templates/image/_description.html.slime
lib/philomena_web/templates/message/_message.html.slime
lib/philomena_web/templates/page/show.html.slime
lib/philomena_web/templates/post/_post.html.slime
lib/philomena_web/templates/post/preview/create.html.slime
lib/philomena_web/templates/profile/_about_me.html.slime
lib/philomena_web/templates/profile/_commission.html.slime
lib/philomena_web/templates/profile/commission/_listing_items.html.slime
lib/philomena_web/templates/profile/commission/_listing_sidebar.html.slime
lib/philomena_web/templates/profile/show.html.slime
lib/philomena_web/templates/tag/_tag_info_row.html.slime

The == operator in Slime inserts iodata marked explicitly as safe. It is quite dangerous and should probably be avoided.

Ensure HTML raw insertion is not used in template

---

lib/philomena_web/templates/tag_change/index.html.slime
lib/philomena_web/views/tag_change_view.ex

---
Retained means the tag change has not been reverted and is still relevant today. I.e. for added tags - the tag is still on the image, for removed tags - the tag is still *not* on the image.
I'm pulling this one from my userscript for derpi and I find this column rather useful. I can see it being useful for mods too.
The word "retained" seemed like the best choice, but it could be confusing to some people. **Alternative approach:** rename column to "Reverted?" and go with "No" on green background and "Yes" on red background. This might be better but I'm not sure …

feat: add "retained" column to tag changes table

---

assets/js/image_expansion.js
lib/philomena_web/controllers/setting_controller.ex
lib/philomena_web/templates/setting/edit.html.slime

---
Add a Local setting to enable autoplaying audio on videos if desired.
Open to moving this around or changing copy, obviously.

Add local setting to enable audio on videos by default

---

docker-compose.yml

This makes it easier to use language integrations like ElixirLS without it conflicting with the Elixir host compile.
Previously this would occur on the Rustler NIF because the container uses musl, and unless your host is Alpine, it probably uses glibc, which would cause a race between the environments -- one would to be unable to load the NIF.
Separating these also properly enables IDE source code navigation and documentation lookup, as well as `mix dialyzer`.
|Documentation|Source code navigation|
|-|-|
|![image](https://github.com/philomena-dev/philomena/assets/9658600/2bc18465-077d-426f-9133-fc3149ae5e5a)|![image](https://github.com/philomena-dev/philomena/assets/9658600/061b2ebb-2b58-48a7-8c08-b5ea16e9c9c5)|

Hide Elixir dependencies from host

---

assets/js/image_expansion.js
assets/js/utils/__tests__/image.spec.ts
assets/js/utils/image.ts

---
Fix audoplaying videos playing under spoilered image pages. Apparently this has been an issue for a while, but it's been exacerbated by #252.

Pause spoilered videos on image pages, unpause on unspoiler

---

lib/philomena/conversations/conversation.ex
lib/philomena/topics/topic.ex

Fixes this deprecation:
```
warning: passing a MFA to :with in cast_assoc/cast_embed is deprecated, please pass an anonymous function instead
(ecto 3.11.1) lib/ecto/changeset/relation.ex:119: Ecto.Changeset.Relation.do_cast/7
(ecto 3.11.1) lib/ecto/changeset/relation.ex:365: Ecto.Changeset.Relation.map_changes/11
(ecto 3.11.1) lib/ecto/changeset/relation.ex:112: Ecto.Changeset.Relation.cast/5
(ecto 3.11.1) lib/ecto/changeset.ex:1278: Ecto.Changeset.cast_relation/4
(philomena 1.1.0) lib/philomena/conversations/conversation.ex:60: Philomena.Conversations.Conversation.creation_changeset/3
(philomena 1.1.0) lib/philomena/conversations.ex:43: Philomena.Conversations.create_conversation/2
```
These were the only two MFA instances used with Ecto. The remaining MFA instances are in …

Fix MFA usage in cast_assoc

---

lib/philomena_query/ip_mask.ex
lib/philomena_web/controllers/ip_profile/source_change_controller.ex
lib/philomena_web/controllers/ip_profile/tag_change_controller.ex
lib/philomena_web/templates/ip_profile/show.html.slime
lib/philomena_web/views/ip_profile_view.ex

Allows seeing IPv6 tag and source changes based on the /64 (or any other mask, but I only expose the /64 in the frontend for now)

Add netmask support to ip_profile tag and source changes

---

lib/philomena/adverts.ex
lib/philomena/adverts/recorder.ex
lib/philomena/adverts/restrictions.ex
lib/philomena/adverts/server.ex
lib/philomena/application.ex
lib/philomena_web/controllers/advert_controller.ex
lib/philomena_web/plugs/advert_plug.ex

Adverts had a couple context warts and this weird GenServer-like creature that wrongly lived in web namespace. As a future todo, the dependency on images is unnecessary and could be completely handled by the caller.

Ads logic cleanup

---

lib/philomena/channels.ex
lib/philomena/channels/automatic_updater.ex
lib/philomena/channels/picarto_channel.ex
lib/philomena/channels/piczel_channel.ex

This removes the updater function body from the context, breaks the backwards dependency between the service API adapters and the updater function, and splits the updates into one per service.

Channel automatic update move

---

lib/philomena_media/gif_preview.ex
lib/philomena_media/processors/webm.ex

Merge https://github.com/philomena-dev/mediatools/pull/2 before this
Fixes stretched video thumbnails by clipping the dimensions of videos encoded with anamorphic resolution (this is always a mistake by the uploader, might be worth also catching this on upload)

Support anamorphic videos

---

lib/philomena/channels.ex
lib/philomena/comments.ex
lib/philomena/forums.ex
lib/philomena/galleries.ex
lib/philomena/images.ex
lib/philomena/posts.ex
lib/philomena/subscriptions.ex
lib/philomena/topics.ex

Notifications are a mess. This cleans up the code for one component of them -- the subscription tables.

Deduplicate common subscription logic

---

assets/css/common/_base.scss
assets/css/views/_notifications.scss
lib/philomena/notifications.ex
lib/philomena/notifications/category.ex
lib/philomena_web/controllers/notification/category_controller.ex
lib/philomena_web/controllers/notification_controller.ex
lib/philomena_web/router.ex
lib/philomena_web/templates/notification/_notification.html.slime
lib/philomena_web/templates/notification/category/show.html.slime
lib/philomena_web/templates/notification/index.html.slime
lib/philomena_web/views/notification/category_view.ex
lib/philomena_web/views/notification_view.ex

Note: this is intended to see if the design is functional before going through with a data migration. If it is then I will also do the data migration to fix the notification tables.
Overview, shows up to 25 of each category, types with no unread notifications not shown
Category page, per_page reduced to 5 to show detail

New notifications UI: separated by category

---

lib/philomena/adverts/recorder.ex
lib/philomena/artist_links/artist_link.ex
lib/philomena/badges/award.ex
lib/philomena/comments.ex
lib/philomena/conversations/conversation.ex
lib/philomena/images.ex
lib/philomena/images/image.ex
lib/philomena/interactions.ex
lib/philomena/poll_votes.ex
lib/philomena/posts.ex
lib/philomena/schema/approval.ex
lib/philomena/tag_changes.ex
lib/philomena/topics.ex
lib/philomena/topics/topic.ex
lib/philomena/users/user.ex
lib/philomena_query/relative_date.ex
lib/philomena_web/stats_updater.ex
lib/philomena_web/user_auth.ex

Ecto automatically rejects format conversions which would lose precision, including storing a date with 1-microsecond precision to a column which only has 1-second precision. For this reason, datetimes must be truncated before storing.
Elixir v1.15 added `DateTime.utc_now/1`, which accepts an argument indicating that the returned value should be truncated, eliminating the need to explicitly truncate it in a second step.

Shorten truncated utc_now pattern

---

lib/philomena/comments/query.ex
lib/philomena/filters/query.ex
lib/philomena/galleries/query.ex
lib/philomena/images/query.ex
lib/philomena/posts/query.ex
lib/philomena/reports/query.ex
lib/philomena/schema/search.ex
lib/philomena/tags/query.ex
lib/philomena_query/parse/parser.ex
lib/philomena_web/controllers/api/json/search/comment_controller.ex
lib/philomena_web/controllers/api/json/search/filter_controller.ex
lib/philomena_web/controllers/api/json/search/gallery_controller.ex
lib/philomena_web/controllers/api/json/search/post_controller.ex
lib/philomena_web/controllers/api/json/search/tag_controller.ex
lib/philomena_web/controllers/comment_controller.ex
lib/philomena_web/controllers/filter_controller.ex
lib/philomena_web/controllers/image/navigate_controller.ex
lib/philomena_web/controllers/post_controller.ex
lib/philomena_web/controllers/tag_controller.ex
lib/philomena_web/image_loader.ex
lib/philomena_web/plugs/filter_forced_users_plug.ex
lib/philomena_web/plugs/image_filter_plug.ex

This makes the usage from callers more idiomatic for use with pipes, and it is now much easier for search modules to get consistent behavior.

New query compile internal API

---

assets/js/settings.ts

This selector is optional and does not exist for the not-logged-in users. We don't really need to assert it existence in this case.
---
This error can be seen in the [settings page](https://derpibooru.org/settings/edit) when user is not authorized:
Because of this error, none of the local settings are getting saved to the `localStorage`. I traced this error back to this snippet asserting the existence of theme selector:
https://github.com/philomena-dev/philomena/blob/2a89162cba104f9c71c946ce902195a213cd02a6/assets/js/settings.ts#L13
Since the selector only exist when …

Fixed Local Settings not properly saving for unauthorized users

---

assets/js/markdowntoolbar.ts

Additionally, these changes contain bugfix for the "Escape" button throwing an error if nothing is selected.
---
Markdown toolbar front-end logic was converted to TypeScript. Overall logic is kept the same, only required type-checks were added.
Also, during the converting, one bug was found and fixed. "Escape" button was throwing an error in user didn't select anything in the `textarea`:
It was caused by the incorrect return in `escapeSelection` function when selected text is empty:
https://github.com/philomena-dev/philomena/blob/073ca2881b15262b61d42163b1ecd9cfda12743 …

Converting markdowntoolbar.js to TypeScript

---

assets/js/autocomplete.ts

---
The issue:
- I'm editing tags
- I'm placing cursor right under the New Tag input
- I'm trying to add some specific tag (for example, `oc only`)
- I'm typing `oc on`
- Autocompleter creates the popup with list of suggested tags
- Since the cursor is placed right where the first tag in the list is located, this tag is getting selected
- If I would press "Enter" in this case, `oc on` would be added as the tag.
If cursor is placed somewhere else, no option is selected. In this case I would need to press "arrow down" and "Enter" and the tag would correctly be added as …

Autocomplete: Prevent autocompleted options from selecting when cursor is placed right where popup is created

---

assets/js/__tests__/upload.spec.ts
assets/js/upload.js
lib/philomena_web/templates/image/new.html.slime

- [ x ] I understand all of the above
---
For the image upload page, this adds client-side tag input validation on form submit. A new handler intercepts the form submit and performs the tag checks. If checks fail, error html is displayed, the submit process is prevented, the upload button is reset, and the page view moves to the top. If instead the checks pass, the form falls through to normal submit behavior.
This does not interfere with or replace server-side tag checks which happen when the form is fully submitted.
The purpose of this PR is to fix the issue of: …

Client-side tag input validation on image upload submit

---

assets/js/autocomplete.ts
assets/js/utils/__tests__/suggestions.spec.ts
assets/js/utils/suggestions.ts

---
This PR mostly attempts to split the code to reduce cognitive complexity.
- All the logic related to displaying & interacting with autocomplete popup was extracted into `SuggestionsPopup` class.
- Now only one actual popup element is getting rendered and re-used for multiple inputs, instead of constantly removing and rendering a new ones every time.
- Function of requesting the server-side suggestions was extracted into `fetchSuggestions` function.
- Caching now happens insight the function, only one request will be sent per term.
- Fixed the term not getting …

Autocomplete: Extracting & slightly refactoring parts of the code

---

lib/mix/tasks/upload_to_s3.ex
lib/philomena/user_downvote_wipe.ex
lib/philomena/workers/tag_change_revert_worker.ex
lib/philomena_query/batch.ex
lib/philomena_query/search.ex

This allows composing the results with the Stream functions. Adapting the callback-based method to do this is possible, but it requires spawning another process, and that is unnecessary because it's actually simpler to write it using Streams anyway.

Change PhilomenaQuery.Batch to Stream-based instead of callback-based

---

lib/philomena_web/markdown_renderer.ex
native/philomena/Cargo.lock
native/philomena/Cargo.toml
native/philomena/src/camo.rs
native/philomena/src/domains.rs
native/philomena/src/lib.rs
native/philomena/src/markdown.rs

1. Changes owning `String` to `&str` in function parameters
2. Changes `String::from("")` to the shorter `"".into()`
3. Moves domain handling to new file in preparation for comrak upgrade PR
4. Removes explicit `HashMap` construction (rustler implements `Decode` for `HashMap<K,V>` when `K` and `V` are `Decode`; the function now raises a badarg if it is not called with a `%{String.t() => String.t()}`)
5. Deduplicates `image_url_careful` code into a single function
6. Sorts dependencies in Cargo.toml by name
7. Removes an unnecessary map construction step in Elixir-side markdown render code

Rust code refactor

---

lib/philomena/data_exports/aggregator.ex
lib/philomena/data_exports/zip_generator.ex
lib/philomena/native.ex
lib/philomena_query/batch.ex
native/philomena/Cargo.lock
native/philomena/Cargo.toml
native/philomena/src/lib.rs
native/philomena/src/zip.rs

This doesn't add any button to trigger the job manually because generation could take longer than 60s. That requires additional work to get the zip streamed to object storage and a job to clean those out after a specific grace period, which will take more time to implement.

Add framework for zip data export

---

lib/philomena_web/templates/commission/_directory_results.html.slime

---
It's a bit uncomfortable to browse the commissions when the pager is only shown at the top of the results.

Display pagination on the bottom of the Commissions page

---

assets/js/autocomplete.ts

---
Noticed that search fields started resetting the original query incorrectly. Instead of restoring the whole query, field gets only the selected term:
[Screencast from 2024-11-14 22-35-08.webm](https://github.com/user-attachments/assets/1f2be359-77e0-43d4-83ab-35964d50823b)
First commit fixes that:
[Screencast from 2024-11-14 22-37-26.webm](https://github.com/user-attachments/assets/4ee4b31b-7af7-45a2-b3c1-5e4f7803c3b9)
Second commit just forces the selection to move to the end of the selected term instead of the end of the whole query:
[Screencast from 2024-11-14 …

Fixed resetting of the auto-completed query not working correctly

---

lib/philomena_proxy/scrapers/bluesky.ex

---
It's possible to use a "did" as a "handle".
For example, these are the same post:
https://bsky.app/profile/did:plc:j3jgpthl5w6avxcenui6s3bn/post/3laueicdbql2f
https://bsky.app/profile/bananitryi.bsky.social/post/3laueicdbql2f

Handle Bluesky "handle" that is a "did"

---

assets/js/markdowntoolbar.ts
lib/philomena/markdown.ex
lib/philomena/markdown/subscript_migrator.ex
lib/philomena/native.ex
lib/philomena/release.ex
native/philomena/Cargo.lock
native/philomena/Cargo.toml
native/philomena/src/lib.rs
native/philomena/src/markdown.rs

This changes the subscript operator to the Pandoc style single tildes (~), and adds a release task to automatically reformat all subscript operators encountered in Markdown text.
Deployment instructions:
First, deploy as usual. Then, select one:
1. Migrate all tables automatically:
`philomena eval "Philomena.Release.migrate_markdown(:all, -1, -1)"`
2. Migrate each table individually or in parallel, with start and end ids:
```
philomena eval "Philomena.Release.migrate_markdown(:images, 0, 100000)" &
philomena eval "Philomena.Release.migrate_markdown(:images, 100000)", 200000)" &
```
Reindexing images, comments, posts, reports and tags is also recommended but not required, since Markdown syntax is ignored by the search stemming engine.

Markdown subscript migration

---

lib/philomena_web/templates/image/_tags.html.slime

---
Right now, if you would try to submit a tag change with blacklisted tag, wait for error to show up and then cancel the editing, block with tag view will disappear from the page:
[Screencast from 2024-12-15 00-30-51.webm](https://github.com/user-attachments/assets/9197038e-a0cd-4b3d-9c74-fc7999330191)
It was caused by the template not marking tags block as being hidden, and JS toggling the hide class. This PR would correctly mark the block as hidden, fixing the problem:
[Screencast from 2024-12-15 00-32-21.webm](https://github.com/user-attachments/assets/d514a543-2c …

Fixed tags block not being hidden on submission error causing it to hide on cancel

---

lib/philomena_media/gif_preview.ex
lib/philomena_media/processors/webm.ex

Fix transparency issues in webm videos

---

lib/philomena/images/dnp_validator.ex
lib/philomena/tags/tag.ex

Makes the logic a bit more efficient than an in-memory filter of relevant tags and N+1 scan of artist links, as well.

Expand DNP validation to all image tags, regardless of prefix

---

lib/philomena_web/templates/image/_image_container.html.slime

---
Disable the picture-in-picture toggle button on image thumbnails when "Use video thumbnails" is enabled.
I'm not sure what the conditions for this rendering actually are, but setting this attribute should hide it everywhere.
This should not affect the image page itself, just thumbnails.

Disable Picture-in-Picture prompt on video thumbnails on Firefox

---

lib/philomena_web/controllers/activity_controller.ex
lib/philomena_web/templates/activity/_channel_strip.html.slime

---
Allow NSFW channels to appear in the "Streams" sidebar entry on the homepage when enabled in Local settings or on the Streams page.
Still a draft as I'm not sure how to make this look better; open for feedback:
**Update:** After some back and forth in the Derpi Discord:

List NSFW channels on Activity page when enabled

---

lib/philomena/search_indexer.ex
lib/philomena_query/search.ex
lib/philomena_query/search/client.ex

Fixes concurrency and defaults issues in the old indexing code that prevented bulk indexing from running as fast as it should have.

Faster indexing

---

lib/mix/tasks/reindex_all.ex
lib/philomena/maintenance.ex
lib/philomena/search_indexer.ex
lib/philomena_query/search.ex

No imports, no aliases. Just easy and fast reindexing with automatic progress reports for production maintenance.
```elixir
iex(1)> Philomena.SearchIndexer.recreate_reindex_schema_destructive!(Philomena.Tags.Tag)
Philomena.Tags.Tag: 433106/753474 [150034/sec], ETA: about 3 second(s)
Philomena.Tags.Tag: 753474/753474 [141754/sec], done.
:ok
```
These will attempt to completely max out the machine to do indexing during a downtime. If this is not desired (e.g., a live reindex), then the following can be used instead to explicitly control the level of concurrency used by the task:
```elixir
Philomena.SearchIndexer.reindex_schema(Philomena.Images.Image, max_concurrency: 2)
```
Functions from the SearchIndexer module:
- `Philomena.SearchIndexer.recreate_reindex_all_destructive!()`: delete, …

 Add reindexing command line with rate and time estimate 

---

assets/js/autocomplete.ts
assets/js/utils/__tests__/local-autocompleter.spec.ts
assets/js/utils/__tests__/unique-heap.spec.ts
assets/js/utils/local-autocompleter.ts
assets/js/utils/unique-heap.ts

I was annoyed that the local completion was performing so poorly on Fennec/mobile Firefox, so I optimized the code to pass around references into the array buffer instead of materializing objects from it, and generally create less garbage on the heap.
This new algorithm takes advantage of the fact that strcmp on UTF-8 byte sequences will produce a lexicographic ordering to skip an extra text decode step--the primary source of the heap garbage. The new algorithm doesn't create zero garbage, but it's much less now, and that gave a nice speedup.
JS performance cannot be measured precisely in Firefox, so here are the numbers for Chrome using the completion binary from Derpibooru:
Average search for "a" before: 18.6ms
Average search for "a" after: 7.8ms

Further optimize clientside autocomplete execution

---

assets/js/upload.js
assets/js/utils/__tests__/events.spec.ts
assets/js/utils/events.ts

---
When user uploads the image and goes back from the image to the upload form, submit button is staying disabled with text "Please wait…". Everything else (description, source URL and tags) is still active and usable.
This PR fixes that by detecting page view from back/forward cache and restoring the button to original state.
Note: I can't replicate the issue on local environment, since there is no back/forward cache. So I've tested this fix on live website through local overrides in DevTools.

Upload Form: Undo submit button disabling from back/forward cache

---

lib/philomena_web/templates/duplicate_report/show.html.slime

---
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-interpolation-filters
default `auto` *sometimes* resolves into `linearRGB` which causes weird diff rendering for identical images

Specify sRGB color space for overlay diff

---

assets/js/autocomplete.ts
lib/philomena_web/templates/filter/_form.html.slime

---
Updated the autocomplete to support `<textarea>` elements. Each line is treated as different search query.
Autocomplete is now turned on for complex spoiler & complex hide filters fields.

Support for textareas, added autocomplete to Complex Spoiler/Hide filter fields

---

assets/js/autocomplete.ts
assets/js/utils/__tests__/suggestions.spec.ts
assets/js/utils/suggestions.ts

---
All aliases would be displayed in the following format:
```
alias ⇒ tag name (count)
```
This change is only updates how aliases displayed from the local autocompleter, server-side suggestions are not updated.

Display alias names for the aliases matched by local autocomplete

---

assets/js/autocomplete.ts
assets/js/utils/__tests__/suggestions.spec.ts
assets/js/utils/suggestions.ts

---
Seems like local autocomplete matches aliases even when prefix is matching the tag itself. This PR stops displaying the alias if prefix matches both alias and the tag name.
Results before and after the change:
And as example, once at least one character starts matching the alias and not the tag, alias will start appearing:

Don't display aliases in suggestions when both alias and tag name are matched by the prefix

---

lib/philomena/images.ex

---
I was not sure where to put it because all other firehose events are broadcast from controllers but there are two controllers that eventually call `merge_image`.
Putting it here ensures the event is called after the merge succeeds and preloading stuff ensures both images are in their before-merge state. 
Closes #326

Broadcast image merges to firehose

---

assets/js/autocomplete.ts
assets/js/utils/__tests__/suggestions.spec.ts
assets/js/utils/local-autocompleter.ts
assets/js/utils/suggestions.ts
assets/js/utils/unique-heap.ts

---
This PR reverts changes made in #416 since issue with aliases is now resolved inside the local autocompleter instance, before results are getting returned for the rendering.

Fixed aliases still displaying for namespaced tags, fixing the actual cause of the issue inside local autocomplete

---

assets/js/utils/dom.ts

---
It's handy to just call `makeEl` and pass the children in one expression, this will be used [here](https://github.com/MareStare/philomena/blob/ef5dd9a379cf7f7dcbd528936b29160a24e7cc42/assets/js/utils/suggestions.ts#L48-L63).

[Part 8] Add an ability to specify child elements to `makeEl`

---

assets/eslint.config.js

---
Had to do the following two changes when working on https://github.com/philomena-dev/philomena/pull/423

[Part 3.5] Allow `expect*` functions in vitest lints and ignore no-extra-parens in eslint

---

lib/philomena_web/controllers/autocomplete/tag_controller.ex

---
Part 1 of the PR https://github.com/philomena-dev/philomena/pull/423. 
I enabled server-side tag completions on all inputs (including the main search). Plus I had to update its backend implementation to return a structured list of suggestions of the following form:
```jsonc
{
"suggestions": [
{
// Name of the alias if this tag aliases some other one, can be absent or null
"alias": "ts",
// Canonical name of the tag, if this suggestion is for the aliases, then this is the alias destination
"canonical": "twilight sparkle",
// Number of images that have this tag …
```

[Part 1] Add server-side suggestions API v2

---

assets/js/utils/__tests__/retry.spec.ts
assets/js/utils/__tests__/store.spec.ts
assets/js/utils/retry.ts
assets/test/mock-date-now.ts
assets/test/mock.ts

---
Added a utility for retries to the frontend. It will be used with the HTTP client utility that I'll post in Part 5

[Part 4] Add a retry utility for frontend

---

assets/js/utils/__tests__/debounced-cache.spec.ts
assets/js/utils/debounced-cache.ts

---
Today, there is an annoying implementation behaviour of debouncing and caching for server-side completions. We debounce user input with a 300ms threshold, then send a server-side completions request and cache its result. However, if the user changes the input and then returns back to the cached input, the user still needs to wait for a 300ms debounce threshold before the cached results are displayed.
I fixed this behaviour and also moved this logic into a generic `DebouncedCache` class. It also manages an `AbortController/AbortSignal`, so that it can cancel the …

[Part 6] Add a DebouncedCache utility for frontend

---

assets/js/utils/__tests__/http-client.spec.ts
assets/js/utils/http-client.ts

---
I added a new `http-client.ts` file with a generic HTTP Client implementation that may be useful for any request from the frontend. It provides a nice API with inbuilt error handling, exponential retries with backoff and jitter, escaping of URL query parameters, and it also adds some useful diagnostic info into the request headers like the `X-Request-Id`, `X-Retry-Sequence-Id`  and `X-Retry-Attempt`.

[Part 5] Add HttpClient utility for frontend

---

assets/js/utils/store.ts

---
This is the core of the machinery used to power real-time updates of the autocompletions when the user changes the settings as demonstrated in the video in the PR description of https://github.com/philomena-dev/philomena/pull/437. Quite niche, but man, it's only `20` lines of simple code plus [this simple subscriber](https://github.com/MareStare/philomena/blob/ef5dd9a379cf7f7dcbd528936b29160a24e7cc42/assets/js/autocomplete/index.ts#L390-L398) that I'll add in followup PR parts.

[Part 7] Emit `'storage-update'` events on local storage update

---

lib/philomena_proxy/scrapers.ex
lib/philomena_proxy/scrapers/civitai.ex

- [☑️] I understand all of the above
---
Added a scraper for CivitAI posts. Only supports /posts/# URLs (not single images) due to API limitations. API also does not provide the "description" visible on the site itself. Meta information like model, prompt, seed, etc. not used as we do not (yet) have a way to store or show this neatly.
Tested locally - cannot confirm preview images work, but locally can't see those from any other source, either.
Possible further work: if given an image URL (rather than posts URL), find the post id on the page and process that. Avoiding …

Add CivitAI post scraper

---

.typos.toml
assets/js/autocomplete/history/index.ts
assets/js/autocomplete/index.ts
assets/js/utils/__tests__/local-autocompleter.spec.ts
assets/js/utils/__tests__/suggestion-model.spec.ts
assets/js/utils/__tests__/suggestion-view.spec.ts
assets/js/utils/dom.ts
assets/js/utils/local-autocompleter.ts
assets/js/utils/suggestions-model.ts
assets/js/utils/suggestions-view.ts

---
This change is only a quick hotfix. What I did is that I added the prefix match inference closer to the UI layer, which I think is wrong and instead the matched parts splitting should happen closer to the match logic itself. I also made the shape of the suggestion a bit more generic such that it now supports matches in random places inside of the string, which may be useful if we do something more complex than just a prefix match.
I did it this way because I didn't want to change the complex matching logic in the `LocalAutocompleter` too much and in server-side …

Fix invalid highlighting of the prefix match for namespaced tags in autocomplete

---

assets/css/themes/base/dark.css
assets/css/themes/base/light.css
assets/css/themes/dark-blue.css
assets/css/themes/dark-gray.css
assets/css/themes/dark-green.css
assets/css/themes/dark-orange.css
assets/css/themes/dark-pink.css
assets/css/themes/dark-purple.css
assets/css/themes/dark-red.css
assets/css/themes/dark-teal.css
assets/css/themes/dark-yellow.css
assets/css/themes/light-blue.css
assets/css/themes/light-gray.css
assets/css/themes/light-green.css
assets/css/themes/light-orange.css
assets/css/themes/light-pink.css
assets/css/themes/light-purple.css
assets/css/themes/light-red.css
assets/css/themes/light-teal.css
assets/css/themes/light-yellow.css
assets/css/views/tags.css
assets/js/utils/__tests__/suggestion-view.spec.ts
assets/js/utils/suggestions-view.ts

---
Changed the selection colours on dark and light themes to use their colours instead of black/white. The stronger highlight (higher) is used for the keyboard selection and a smaller highlight (lower) is for mouse on-hover on the screenshots below.
What isn't done in this PR is that I haven't switched the layout to a table yet. Will do it tomorrow.
The mouse on-hover was absolutely invisible:
Added `Consolas` and some `Noto Sans Mono` that was used in Liam's browser in hope of getting a better monospace font by default. But even if the browser falls back to `Courier …

Hotfix the color styling and fonts for autocompletions

---

assets/css/views/tags.css

---
This font happens to be present on my Ubuntu 24 laptop, and it renders the arrow better than  `Noto` does, so adding it as a better alternative before them:
How `Noto` renders it:

Add `DejaVu Sans Mono` as a font that correctly renders an `→`

---

assets/eslint.config.js
assets/js/utils/__tests__/suggestion-view.spec.ts
assets/js/utils/suggestions-view.ts

---
Fixes that small dot in the corner of the input when there 0 suggestions to show:

Hide the autocomplete popup entirely if there are no items to show

---

assets/js/burger.ts
assets/js/interactions.js

---
Tested this manually. For images with disabled downvotes - just hardcoded an image ID `5` in the array temporarily and checked that it works.

Get rid of `stopPropagation` on `click` events to make autocomplete popup disappear

---

assets/css/elements/forms.css
assets/js/settings.ts
lib/philomena_web/templates/setting/edit.html.slime
lib/philomena_web/views/setting_view.ex

---
Here is the new look of the settings UI:
<details>
<summary>Display</summary>
</details>
<details>
<summary>Comments</summary>
</details>
<details>
<summary>Notifications</summary>
</details>
<details>
<summary>Metadata</summary>
</details>
<details>
<summary>Local</summary>
</details>
If you hover over the "Help" button it becomes highlighted and if you press on this button the description of the field will expand:
We can make the "Help" button rectangle, which would follow the rectangle style of the site, but IMO it looks less pleasing:
**Changes:**
- Swapped …

Settings UI improvements: help button, input/label reorder, no flex, etc

---

docker/app/Dockerfile

---
This PR cherrypicks a commit from https://github.com/philomena-dev/philomena/pull/481

Remove now useless `COPY` instructions because we use a volume bind-mount instead

---

lib/philomena/tags/tag.ex

---
Old `commissioner:*` tags will need to have namespace fixed

Make commissioner a valid namespace

---

lib/philomena/images/query.ex
lib/philomena_query/parse/parser.ex

---
Closes #502
Introduces a new normalizations map for parser and applies proper `clean_tag_name` to tag terms

Normalize tag names in search queries

---

docker/web/Dockerfile

---
Caddy S3 FS module requires higher go version, failing the build otherwise.

Bump Caddy version to 2.10.0

---

assets/css/views/tags.css
assets/js/tags.ts
assets/js/utils/dom.ts
lib/philomena_web/templates/tag/_tag.html.slime

---
The CSS `has()` selector is too new (2023 baseline), so changed the `tags.css` impl to add/remove classes `tag--{state}` for the tag instead

Replace css `has()` with manual state management

---

lib/philomena/users.ex
lib/philomena/users/ability.ex
lib/philomena_web/templates/admin/user/_form.html.slime

Fix Canada checks for users with multiple roles of the same resource type

---

lib/philomena/comments.ex
lib/philomena/image_faves.ex
lib/philomena/image_votes.ex
lib/philomena/images.ex
lib/philomena/posts.ex
lib/philomena/user_statistics.ex
lib/philomena_web/controllers/image/comment/approve_controller.ex
lib/philomena_web/controllers/image/comment_controller.ex
lib/philomena_web/controllers/image/source_controller.ex
lib/philomena_web/controllers/image/tag_controller.ex
lib/philomena_web/controllers/topic/post_controller.ex

---
Accept id instead of object to avoid preloading
Fixes approving a comment incrementing `comments_posted` twice

Update UserStatistics.inc_stat to accept user_id

---

assets/js/tagsmisc.ts
assets/js/utils/__tests__/assert.spec.ts
assets/js/utils/assert.ts

---
Found this when testing clicks on profile images. Turns out this bug also exists in the production version of derpibooru. To reproduce you need go to any page that displays the profile image of the user. For example, look at the comments for [this image](https://derpibooru.org/images/3596936?q=my%3Awatched), click on "Captain Goon Saint"'s user profile image SVG, and you'll see this in console:
This PR fixes that error by widening the type check in `tagsmisc` from `HTMLElement` to just `Element`.
Also improved the error logging in case if assert fails

Fix throwing an error when clicking on the user profile image SVG

---

.gitattributes
assets/js/__tests__/upload.spec.ts
assets/js/ecmascript-compat-test.ts
assets/package.json
assets/tsconfig.build.json
assets/tsconfig.json
assets/vite.config.ts

---
See more details on the nuance this fixes in the extensive comment in `tsconfig.json`

Make sure our frontend compiles with `es2019` maximum

---

lib/philomena_query/parse/bool_parser.ex
lib/philomena_query/parse/date_parser.ex
lib/philomena_query/parse/float_parser.ex
lib/philomena_query/parse/int_parser.ex
lib/philomena_query/parse/ip_parser.ex

---
Term range parser trims the input before passing it onto other parsers

Remove space handling from parsers

---

assets/eslint.config.js
assets/js/autocomplete/history/store.ts
assets/js/boorujs.js
assets/js/comment.js
assets/js/fp.ts
assets/js/interactions.js
assets/js/preview.js
assets/js/query/user.ts
assets/js/ujs.ts
assets/js/upload.js
assets/js/utils/__tests__/image.spec.ts
assets/js/utils/__tests__/suggestion-view.spec.ts
assets/js/utils/dom.ts
assets/js/utils/draggable.ts
assets/js/utils/events.ts
assets/js/utils/suggestions-view.ts
assets/js/utils/unique-heap.ts
assets/test/mock-storage.ts
assets/tsconfig.json

---
My goal is to reduce the eslint config as much as possible plus enable lints that require type info (currently they trigger a lot of lints, so I haven't done this yet). This doesn't achieve that goal fully, but already removes some redundant configs from our `eslint.config.js`.

Small eslint config cleanup, use strict and stylistic lints

---

docker-compose.yml
lib/philomena/application.ex
lib/philomena/images/thumbnailer.ex

---
I've been debugging way too many things with the https://github.com/philomena-dev/philomena/pull/481, and the lack of the logs has been a really big problem. I haven't found a good way to configure filtering the logs from different modules and third-party libraries dynamically with Elixir's logger, so I rolled my own solution with the `PHILOMENA_LOG` env var.
Also had to add more logs to some places to see what's actually happening there. For example, there was a bug in `s3-proxy` with uploading large files, but the error wasn't properly logged, now it is:
You can …

Add `tracing`'s `EnvFilter`-like log filtering with `PHILOMENA_LOG` env var

---

lib/philomena_media/objects.ex

The prerequisite for this PR is https://github.com/philomena-dev/philomena/pull/495
Now we can see the exact cause of errors uploading to S3
With the debug level logs enabled we can also see the exact S3 operations performed:

Add more logs for S3 operations

---

lib/philomena/tag_changes.ex
lib/philomena_web/controllers/image/tag_controller.ex
lib/philomena_web/controllers/image_controller.ex
lib/philomena_web/templates/image/_source.html.slime
lib/philomena_web/templates/image/_tags.html.slime
lib/philomena_web/templates/image/show.html.slime

Add total tags changed to History on image page

---

lib/philomena_web/templates/tag_change/index.html.slime
lib/philomena_web/views/tag_change_view.ex

Display order for tag change tags is currently inconsistent

Sort tag change tags

---

assets/js/image_expansion.js
lib/philomena/adverts/advert.ex
lib/philomena/images/image.ex
lib/philomena/users/user.ex
lib/philomena_media/sha512.ex
lib/philomena_proxy/http.ex
lib/philomena_web/endpoint.ex
lib/philomena_web/templates/avatar/edit.html.slime
lib/philomena_web/templates/image/_image_meta.html.slime

- Bumps advert file size from 750 KB to 1 MiB
- Bumps image file size from 125 MB to 125 MiB
- Bumps user avatar file size from 300 KB to 500 KiB
- Bumps proxy response body limit to 125 MiB
- Bumps request body size limit to 130 MiB
- Uses more sane units

Bump some limits and better units

---

lib/philomena_web/controllers/registration_controller.ex
lib/philomena_web/user_auth.ex

Records user's IP and FP after a successful registration. This solves a potential attack vector.`Last seen (never)` is no longer possible as a result.
Closes #587

Update usages after registration

---

lib/philomena/comments.ex
lib/philomena/comments/comment.ex
lib/philomena/conversations.ex
lib/philomena/conversations/message.ex
lib/philomena/posts.ex
lib/philomena/posts/post.ex
lib/philomena/schema/approval.ex
lib/philomena/users.ex
lib/philomena_web/templates/comment/_comment.html.slime
lib/philomena_web/templates/conversation/new.html.slime
lib/philomena_web/templates/conversation/show.html.slime
lib/philomena_web/templates/post/_post.html.slime
lib/philomena_web/views/app_view.ex
lib/philomena_web/views/conversation_view.ex

- Flags all posts and comments with external links from untrusted users for review
- Trusted means a verified account or an account older than 2 weeks
- Approval logic for conversation messages remains the same (flag image embeds)
- Checks users About Me and Personal Title for external links and creates system reports

Strict approval

---

lib/philomena/reports.ex
lib/philomena/users/eraser.ex

Following #611, many bots will have system reports against them. This makes "Erase for spam" automatically close them.

Close reports on user erase

---

lib/philomena/conversations.ex
lib/philomena/users/ability.ex
lib/philomena_web/templates/message/_message.html.slime

- Fixes mods not actually having access to approve conversation messages
- Fixes approving messages resulting in an error
- Hides unapproved messages from users
- - Both participants will see a "This private message is pending approval" banner
- - Only the sender will see the contents until approved
**Note:** we will need to retroactively approve all existing messages

Conversation messages approval

---

.gitignore

---
Formatter was added a while ago into the root of repository, but `node_modules` directory wasn't added to `.gitignore`. This PR fixes that.

Fixed root `node_modules` missing from `.gitignore`
