philomena-dev/philomena

- lib/philomena/tags/tag.ex
- lib/philomena_web/plugs/limit_plug.ex
---
Adds a series of checks for staff roles and allows any of them to bypass rate limits that use this plug.
> Allow staff to bypass rate limits

- lib/philomena/elasticsearch.ex
- lib/philomena/interactions.ex
- lib/philomena_web/controllers/gallery_controller.ex
- lib/philomena_web/controllers/image/navigate_controller.ex
- lib/philomena_web/controllers/search_controller.ex
- lib/philomena_web/image_loader.ex
- lib/philomena_web/image_navigator.ex
- lib/philomena_web/image_scope.ex
- lib/philomena_web/image_sorter.ex
- lib/philomena_web/param.ex
- lib/philomena_web/templates/gallery/show.html.slime
- lib/philomena_web/templates/image/index.html.slime
- lib/philomena_web/templates/search/_form.html.slime
Fixes _all_ navigation related issues, and lays the groundwork for enabling index sorting for more efficient returning of sorted results.
> Search navigation

- lib/philomena_web/plugs/limit_plug.ex
---
Add ability to bypass the staff exemption in `PhilomenaWeb.LimitPlug` with `skip_staff: false`.
> Damaged limit staff skip

- lib/philomena_web/templates/admin/user/index.html.slime
- lib/philomena_web/templates/layout/_header_staff_links.html.slime
- lib/philomena_web/templates/tag/edit.html.slime
Admin bar, B/A dropdowns for assistants
Tag processing and aliases if you don't have admin tag editing perm
Edit button on users list
> Minor cleanup related to staff perms

- docker-compose.yml
Fixes Fedora launch error, probably others
> Better default for CDN_HOST

- assets/js/shortcuts.js
> Added new shortcut to open full images 'V'. Changed behavior to open new tab.

- config/config.exs
- config/runtime.exs
- lib/philomena/comments.ex
- lib/philomena/galleries.ex
- lib/philomena/images.ex
- lib/philomena/posts.ex
- lib/philomena/reports.ex
- lib/philomena/tags.ex
- lib/philomena/topics.ex
- lib/philomena/user_downvote_wipe.ex
- lib/philomena/user_wipe.ex
- lib/philomena/users.ex
- lib/philomena/workers/gallery_reorder_worker.ex
- lib/philomena/workers/index_worker.ex
- lib/philomena/workers/notification_worker.ex
- lib/philomena/workers/tag_alias_worker.ex
- lib/philomena/workers/tag_delete_worker.ex
- lib/philomena/workers/tag_reindex_worker.ex
- lib/philomena/workers/tag_unalias_worker.ex
- lib/philomena/workers/user_rename_worker.ex
- lib/philomena/workers/user_unvote_worker.ex
- lib/philomena/workers/user_wipe_worker.ex
- lib/philomena_web/controllers/admin/user/downvote_controller.ex
- lib/philomena_web/controllers/admin/user/vote_controller.ex
- lib/philomena_web/controllers/admin/user/wipe_controller.ex
- lib/philomena_web/controllers/tag/alias_controller.ex
- lib/philomena_web/controllers/tag/reindex_controller.ex
- lib/philomena_web/controllers/tag_controller.ex
No particular changes necessary for deployment.
> Remove spawn calls

- assets/js/utils/image.js
> Use even larger thumb if normal size is medium already

- lib/philomena/images.ex
- lib/philomena/images/image.ex
- lib/philomena/images/tag_differ.ex
- lib/philomena/images/tag_lock.ex
- lib/philomena_web/controllers/image/tag_controller.ex
- lib/philomena_web/controllers/image/tag_lock_controller.ex
- lib/philomena_web/controllers/image_controller.ex
- lib/philomena_web/router.ex
- lib/philomena_web/templates/image/_options.html.slime
- lib/philomena_web/templates/image/_tags.html.slime
- lib/philomena_web/templates/image/tag_lock/show.html.slime
- lib/philomena_web/views/image/tag_lock_view.ex
- priv/repo/migrations/20210301012137_add_tag_locks.exs
- priv/repo/structure.sql
Fixes derpibooru/philomena#238
Fixes derpibooru/philomena#170
Allows locking specific tags on any image. Any attempts to add or remove tags in the list are silently ignored.
> Tag locking

- assets/js/shortcuts.js
> Reverted behavior on 'O' shortcut to open image in same tab

- lib/philomena_web/templates/dnp_entry/index.html.slime
- [✅] I understand all of the above
---
Literally just fixes a typo, was pointed out on the forums awhile ago and no one fixed it.
> Fixes typo on DNP page

- config/footer.json
- lib/philomena_web/templates/layout/_footer.html.slime
---
By adding a "new_tab" property to a link and setting it to true in footer.json, the link will be opened in a new tab. I find this useful for opening external links such as the Twitter link.
> Add the option to open footer links in a new tab

- assets/css/views/_images.scss
- assets/js/upload.js
- lib/philomena_web/plugs/content_security_policy_plug.ex
Adds proper upload previews for uploaded video files.
> Video upload previews

- assets/js/autocomplete.js
- assets/js/utils/local-autocompleter.js
- docker/app/run-development
- lib/philomena/autocomplete.ex
- lib/philomena/autocomplete/autocomplete.ex
- lib/philomena/release.ex
- lib/philomena_web/controllers/autocomplete/compiled_controller.ex
- lib/philomena_web/router.ex
- priv/repo/migrations/20211219194836_create_autocomplete.exs
- priv/repo/structure.sql
Production update involves adding a daily cronjob to update the compiled autocomplete; see changes to run-development for what to run.
> Local autocomplete

- assets/css/views/_images.scss
- assets/js/image_expansion.js
- assets/js/preview.js
- lib/philomena_web/markdown_renderer.ex
- lib/philomena_web/templates/image/_image_target.html.slime
- lib/philomena_web/templates/layout/_opengraph.html.slime
- lib/philomena_web/views/image_view.ex
This also fixes having multiple image_target nodes on the page.
> Fix embedded image views for small images

- lib/philomena/galleries.ex
Solves the mysterious lingering notification bug
> Fix gallery notification deletion

- lib/philomena_web/views/image_view.ex
---
added 2 mastodon instances to the list for the mastodon icon
> added 2 mastodon instances where I found pony artists on

- assets/js/match_query.js
---
`getAttribute` returns string. `window.booru.interactions` has number image ids
> Fix my:faves, my:upvotes, my:downvotes in complex filters

- lib/philomena/scrapers/twitter.ex
This also bypasses the login wall for all images
> switch to maintained twitter scraper implementation

- lib/philomena/scrapers/twitter.ex
---
Twitter images can be png, e.g.:
- https://twitter.com/ChaosAngelDesu/status/1071752621667565568
- api: https://api.fxtwitter.com/ChaosAngelDesu/status/1071752621667565568
`large` isn't the highest quality. that would be `4096x4096` or `orig`, e.g.:
- https://twitter.com/zokkili/status/1756303167158174101
- api: https://api.fxtwitter.com/zokkili/status/1756303167158174101
- https://pbs.twimg.com/media/GF-jwqxbsAAnS9G.jpg:large
- https://pbs.twimg.com/media/GF-jwqxbsAAnS9G.jpg:orig
> Improve twitter scraper

- lib/philomena/images/query.ex
- lib/philomena_web/templates/search/_form.html.slime
> Search images by file name

- lib/philomena/images/query.ex
- lib/philomena/search/parser.ex
> parser: don't downcase some fields

- lib/philomena_web/views/image_view.ex
---
I also refactored this `case`. I'm not sure if this is conventional elixir but it feels more readable.
edit: turns out that was illegal. reverted.
> ImageView: add more hosts for source icons

- lib/philomena/scrapers/twitter.ex
> scrapers/twitter: support x.com

- assets/js/misc.js
- assets/js/sources.js
- lib/philomena_web/templates/image/_source.html.slime
> fix sources block not updating properly after saving

- lib/philomena_web/views/image_view.ex
> feat: more icons for source urls

- lib/philomena/scrapers/twitter.ex
> Twitter scraper description

- lib/philomena_web/templates/search/index.html.slime
> feat(search): force display dnp entries even if found no images

- lib/philomena_web/controllers/profile/tag_change_controller.ex
- lib/philomena_web/templates/profile/tag_change/index.html.slime
From https://derpibooru.org/forums/meta/topics/feature-suggestions-and-discussion?post_id=5606524#post_5606524
> Tag change search

- assets/css/common/_blocks.scss
- assets/css/common/_header.scss
- assets/css/views/_images.scss
- assets/css/views/_tags.scss
- lib/philomena_web/templates/layout/_header_navigation.html.slime
Make stylesheets and HTML whitespace tolerant. To be updated as I find additional instances of issues.
> Whitespace tolerance

- config/quick_tag_table.json
> feat: add "oc only" to quick tag table Often Forgotten

- lib/philomena/images/thumbnailer.ex
---
This PR attempts to fix an issue where Cloudflare would cache the original unprocessed image indefinitely by purging cache after a processor asks to replace the original `full.ext` file.
```bash
$ curl -Is https://derpicdn.net/img/download/2024/5/4/3357501.png | grep -i content-length
content-length: 16570965
$ curl -Is https://derpicdn.net/img/2024/5/4/3357501/full.png | grep -i content-length
content-length: 21585362
```
I cannot really test this fix.
> Fix Cloudflare caching unprocessed images

- lib/philomena_web/plugs/user_attribution_plug.ex
> Truncate incoming referrer string

- lib/philomena/autocomplete/autocomplete.ex
- lib/philomena/sha512.ex
- lib/philomena_web/config.ex
See individual commit names for more information.
> Fix Dialyzer

- assets/css/views/_tags.scss
- assets/js/autocomplete.js
---
- Fixed the z-index position of the autocomplete window 
- Fixed terms not being lower-cased before sending them to the auto-completion class
> Minor fixes for the auto-completion

- lib/philomena/images.ex
- lib/philomena/images/image.ex
- lib/philomena_web/templates/image/_source.html.slime
- lib/philomena_web/templates/image/new.html.slime
---
not enough. this limit is actually not enforced server-side which I'm not sure if intentional
> Bump max source count to 15

- .github/workflows/elixir.yml
- .typos.toml
- assets/js/utils/__tests__/local-autocompleter.spec.ts
- lib/philomena/tags.ex
- lib/philomena/users/user_notifier.ex
- lib/philomena_web/controllers/admin/site_notice_controller.ex
- lib/philomena_web/templates/conversation/show.html.slime
- lib/philomena_web/templates/filter/_form.html.slime
- lib/philomena_web/templates/topic/poll/_form.html.slime
> Small CI improvements

- lib/philomena_media/gif_preview.ex
- lib/philomena_media/processors/webm.ex
Replaces and documents the old system to properly deal with videos have that variable FPS.
> Timebase independent video GIF previewer

- assets/js/notifications.ts
- assets/js/utils/events.ts
- assets/js/utils/store.ts
works in dev but i didn't test dynamic notif count updater because i'm slowly exceeding my balmer's peak
> convert notifications to typescript

- assets/js/misc.ts
> convert misc scripts to ts

- lib/philomena/images/source.ex
- lib/philomena/images/source_differ.ex
Fixes https://derpibooru.org/forums/meta/topics/report-site-bugs-here?post_id=5627362#post_5627362
> Extended source validation

- lib/philomena/channels.ex
- lib/philomena/channels/channel.ex
- lib/philomena/tags.ex
Schema modules probably shouldn't have repo fetches in them
> Remove Repo fetch from Channel module

- lib/philomena/duplicate_reports.ex
- lib/philomena_web/controllers/api/json/search/reverse_controller.ex
- lib/philomena_web/image_reverse.ex
> feat: support limit param in reverse search

- lib/philomena/users.ex
- lib/philomena/users/eraser.ex
- lib/philomena/workers/user_erase_worker.ex
- lib/philomena_web/controllers/admin/user/erase_controller.ex
- lib/philomena_web/router.ex
- lib/philomena_web/templates/admin/user/erase/new.html.slime
- lib/philomena_web/templates/profile/_admin_block.html.slime
- lib/philomena_web/views/admin/user/erase_view.ex
Should help with dealing with persistent spammers
> Add more thorough user change eraser

- lib/philomena/comments.ex
- lib/philomena/conversations.ex
- lib/philomena/images.ex
- lib/philomena/posts.ex
- lib/philomena/reports.ex
- lib/philomena_web/controllers/conversation/report_controller.ex
- lib/philomena_web/controllers/gallery/report_controller.ex
- lib/philomena_web/controllers/image/comment/report_controller.ex
- lib/philomena_web/controllers/image/report_controller.ex
- lib/philomena_web/controllers/profile/commission/report_controller.ex
- lib/philomena_web/controllers/profile/report_controller.ex
- lib/philomena_web/controllers/report_controller.ex
- lib/philomena_web/controllers/topic/post/report_controller.ex
- lib/philomena_web/plugs/admin_counters_plug.ex
Documentation and consistency cleanups.
> More reports cleanups

- assets/js/markdowntoolbar.js
- assets/js/shortcuts.ts
---
`keyCode` may be deprecated but it provides a more convenient behavior regarding different keyboard layouts
> use keyCode instead of key

- lib/philomena/duplicate_reports/search_query.ex
- lib/philomena_web/templates/search/reverse/index.html.slime
> Some reverse search fixes

- lib/philomena/conversations.ex
- lib/philomena/conversations/conversation.ex
- lib/philomena/conversations/message.ex
- lib/philomena/users.ex
- lib/philomena_web/controllers/conversation/message/approve_controller.ex
- lib/philomena_web/controllers/conversation/message_controller.ex
- lib/philomena_web/controllers/conversation_controller.ex
- lib/philomena_web/templates/conversation/index.html.slime
This is a big cleanup of all conversations logic, which aims to document the context, break dependencies between frontend and backend, and declutter the controller.
> Conversations cleanup

- assets/js/autocomplete.ts
---
Just converting the auto-completion logic to TypeScript. Logic itself is mostly untouched, except for type-checks required to "comply" with types.
> Converting autocomplete.js to TypeScript

- assets/js/autocomplete.ts
- assets/js/utils/__tests__/events.spec.ts
- assets/js/utils/events.ts
> Add mouseMoveThenOver, test

- .github/workflows/elixir.yml
- native/philomena/src/camo.rs
- native/philomena/src/markdown.rs
Adds rust lints (cargo fmt and clippy) and elixir formatting (mix format)
> Extra lint jobs

- .github/workflows/elixir.yml
- native/philomena/Cargo.lock
- native/philomena/Cargo.toml
- native/philomena/src/domains.rs
- native/philomena/src/lib.rs
- native/philomena/src/markdown.rs
- native/philomena/src/tests.rs
Much of the functionality has been moved upstream / genericized in some way, so the main tests are copied to this repository to ensure that all of the relevant functionality is enabled in the options.
> Update to Philomena comrak v0.29.0

- assets/js/__tests__/tagsinput.spec.ts
- assets/js/tagsinput.ts
- assets/test/vitest-setup.ts
- assets/types/booru-object.d.ts
- assets/types/tags.ts
Pretty much just a straight port. 100% test coverage
> Convert tagsinput to TypeScript

- lib/philomena_web/controllers/image/source_controller.ex
- lib/philomena_web/controllers/image_controller.ex
[As reported](https://derpibooru.org/forums/meta/topics/report-site-bugs-here?post_id=5673492#post_5673492)
> Fix single-source saving bug

- assets/js/tagsinput.ts
[as here](https://derpibooru.org/forums/meta/topics/report-site-bugs-here?post_id=5674440#post_5674440)
> Scope tag input select to tag block

- assets/js/autocomplete.ts
- assets/js/tagsinput.ts
---
- Fixes #382
[Screencast from 2024-12-15 00-03-49.webm](https://github.com/user-attachments/assets/96df8691-e2ae-4130-8bce-03f83f2a3e10)
The syntax works for both local & server-side auto-complete.
> Support suggestions when using `-tag` syntax in tag editor

- docker/app/Dockerfile
> Elixir 1.18

- .dialyzer_ignore.exs
- .github/workflows/elixir.yml
- docker/app/run-test
- mix.exs
> Force GH Actions workflows to use test env

- assets/css/elements/base.css
- assets/css/views/tags.css
These changes were anonymously requested/contributed [here](https://derpibooru.org/forums/meta/topics/new-themes-and-stylesheets?post_id=5688435#post_5688435) and [here](https://derpibooru.org/forums/meta/topics/new-themes-and-stylesheets?post_id=5689967#post_5689967).
> CSS improvements

- docker/app/Dockerfile
> Split long line in the app Dockerfile

- assets/eslint.config.js
- assets/js/query/parse.ts
- assets/js/utils/assert.ts
- assets/js/utils/tag.ts
- assets/js/utils/unique-heap.ts
---
This lint no longer makes sense in modern TypeScript code.
> Disable `no-undefined` ESLint lint

- lib/philomena_web/controllers/fingerprint_profile/source_change_controller.ex
- lib/philomena_web/controllers/ip_profile/source_change_controller.ex
- lib/philomena_web/controllers/profile/source_change_controller.ex
- lib/philomena_web/templates/fingerprint_profile/source_change/index.html.slime
- lib/philomena_web/templates/ip_profile/source_change/index.html.slime
- lib/philomena_web/templates/profile/source_change/index.html.slime
> Implement added filters and image count to source changes pages

- assets/.stylelintrc.yml
- assets/css/common/measurements.css
- assets/css/views/communications.css
- assets/css/views/profiles.css
- lib/philomena_web/templates/admin/report/show.html.slime
- lib/philomena_web/templates/comment/_comment.html.slime
- lib/philomena_web/templates/comment/_comment_with_image.html.slime
- lib/philomena_web/templates/image/comment/history/index.html.slime
- lib/philomena_web/templates/message/_message.html.slime
- lib/philomena_web/templates/post/_post.html.slime
- lib/philomena_web/templates/post/preview/create.html.slime
- lib/philomena_web/templates/topic/post/history/index.html.slime
mobile communications less sucky wucky uwu
> move communication text below avatar on mobile

- assets/js/autocomplete.ts
- assets/js/utils/__tests__/local-autocompleter.spec.ts
- assets/js/utils/suggestions.ts
- lib/philomena_web/templates/filter/_form.html.slime
- lib/philomena_web/templates/layout/_header.html.slime
- lib/philomena_web/templates/profile/artist_link/_form.html.slime
- lib/philomena_web/templates/search/_form.html.slime
- lib/philomena_web/templates/tag/_tag_editor.html.slime
---
I've been just reading the code so far, and I did some small improvements to autocomplete/tag inputs code. Created a PR to merge them separately:
- Split huge lines into several
- Renamings for better clarity
- Extract shared function
- Move variables closer to their usage
- Add more comments for more context
> Refactoring of autocomplete and tag inputs

- assets/css/application.css
---
Thanks to anon for research here https://derpibooru.org/forums/meta/topics/report-site-bugs-here?post_id=5677994#post_5677994
Semi-consistent way to reproduce the issue:
1. Open DevTools
2. Check "Disable cache" in Network
3. Reload the page
4. Close devtools shortly after that (you need to get the timing right)
> Specify utf-8 charset for css

- lib/philomena_web/controllers/admin/batch/tag_controller.ex
> Broadcast batch tag updates to firehose

- lib/philomena_web/plugs/content_security_policy_plug.ex
---
This change allows connecting to a local instance on a private IP in dev environments.
> [Part 3] Relax CSP in dev env to allow for private IPs

- lib/philomena/autocomplete/generator.ex
> Add more docs to the local autocomplete binary layout

- lib/philomena/reports/query.ex
> Fix reportable_type search

- lib/philomena_web/templates/setting/edit.html.slime
> Fix grammar in the Settings > Notifications > Subscribe on Reply

- lib/philomena_web/controllers/autocomplete/tag_controller.ex
---
Fixes a bug reported by anon in the [forum thread](https://derpibooru.org/forums/meta/topics/site-development-notification-and-feedback-thread?post_id=5708725#post_5708725)
> Add client-side sorting to server-side autocomplete to work around data desync bugs

- .gitattributes
- .githooks/pre-commit
- .github/workflows/elixir.yml
- .gitignore
- .vscode/extensions.json
- README.md
- scripts/init.sh
---
Added a helpful script for initial dev setup and some instructions to the README.md
Plus fixed the pre-commit hook to auto-format the Elixir code instead of failing with an error if Elixir code is not formatted.
> Add init script and instructions for dev setup

- .githooks/pre-commit
- assets/js/utils/suggestions-view.ts
- docker/app/Dockerfile
- docker/app/run-development
- scripts/init.sh
- scripts/lib.sh
---
Added command logging with color highlight to the dev scripts, so now the logs look like this:
Pre-commit hook:
Repo init script:
> Add better logging to `run-development`, `pre-commit`, `init.sh` scripts

- assets/js/autocomplete/__tests__/context.ts
> Fix the grammar in autocomplete test context comment

- lib/philomena_web/controllers/admin/artist_link_controller.ex
- lib/philomena_web/controllers/admin/dnp_entry_controller.ex
- lib/philomena_web/controllers/admin/fingerprint_ban_controller.ex
- lib/philomena_web/controllers/admin/subnet_ban_controller.ex
- lib/philomena_web/controllers/admin/user_ban_controller.ex
- lib/philomena_web/controllers/admin/user_controller.ex
- lib/philomena_web/templates/admin/artist_link/index.html.slime
- lib/philomena_web/templates/admin/dnp_entry/index.html.slime
- lib/philomena_web/templates/admin/fingerprint_ban/index.html.slime
- lib/philomena_web/templates/admin/subnet_ban/index.html.slime
- lib/philomena_web/templates/admin/user/index.html.slime
- lib/philomena_web/templates/admin/user_ban/index.html.slime
- lib/philomena_web/templates/search/_form.html.slime
- lib/philomena_web/views/admin/ban_view.ex
- lib/philomena_web/views/admin/user_view.ex
> Use unique input names for search forms

- lib/philomena_web/controllers/tag/reindex_controller.ex
> Reindex tag itself on "Rebuild index"

- lib/philomena_web/controllers/admin/dnp_entry/transition_controller.ex
> Log DNP entry transitions

- lib/philomena_web/templates/search/index.html.slime
- lib/philomena_web/views/search_view.ex
---
- tags with more than 0 images
- empty tags with mod notes
> Update override display logic for tags

- lib/philomena/tags/tag.ex
> Fix clean_tag_name

- lib/philomena_web/controllers/image/tag_change_controller.ex
> Fix deleting tag changes where tag is nil

- lib/philomena/images/query.ex
> Allow searching images by anonymous field

- lib/philomena/images/image.ex
- lib/philomena_web/controllers/image/approve_controller.ex
> Image approval checks

- lib/philomena/images/image.ex
- lib/philomena_web/controllers/image/approve_controller.ex
> Allow approving deleted images

- assets/js/interactions.js
---
Reported in Discord: https://discord.com/channels/430829008402251796/662895347911098368/1362465559656005835
> Fix: allow downvoting on image pages (even if hidden/spoilered) again

- lib/philomena_web/controllers/image/comment/hide_controller.ex
- lib/philomena_web/controllers/image/delete_controller.ex
- lib/philomena_web/controllers/image/destroy_controller.ex
- lib/philomena_web/controllers/image/feature_controller.ex
- lib/philomena_web/controllers/image/file_controller.ex
- lib/philomena_web/controllers/topic/hide_controller.ex
- lib/philomena_web/controllers/topic/post/hide_controller.ex
- lib/philomena_web/templates/image/_options.html.slime
---
Updates user-facing language hide -> delete, unhide -> restore
> Consistent deletion terminology

- lib/philomena_web/templates/profile/show.html.slime
> Link to true_uploader for mods

- assets/js/utils/suggestions-view.ts
---
This fixes [the CI](https://github.com/philomena-dev/philomena/actions/runs/14699613647/job/41246710198?pr=528) on my devcontainer PR, because Alpine Linux seems to have ICU packages missing in its default nodejs installation. Anyway, intended to remove Intl dependency for some time already
> Do manual number formatting for cross platform stability

- lib/philomena/reports.ex
> Fix autoclosing reports overriding admin_id

- docker/app/run-development
> Apply pending migrations and reindex if needed in `run-development`

- lib/philomena/images.ex
- lib/philomena/images/image.ex
- lib/philomena_web/controllers/admin/approval_controller.ex
- priv/repo/migrations/20250502110018_approve_deleted_images.exs
- priv/repo/structure.sql
> Approve deleted images

- lib/philomena_web/controllers/search_controller.ex
- lib/philomena_web/image_navigator.ex
- lib/philomena_web/image_sorter.ex
> Fix sorting in image navigator

- lib/philomena_web/templates/admin/artist_link/index.html.slime
- lib/philomena_web/views/admin/artist_link_view.ex
> Fix scope for artist link page

- lib/philomena_web/controllers/image_controller.ex
> Retain scope on /images

- lib/philomena_web/templates/admin/advert/index.html.slime
- lib/philomena_web/templates/admin/approval/index.html.slime
- lib/philomena_web/templates/admin/artist_link/index.html.slime
- lib/philomena_web/templates/admin/badge/index.html.slime
- lib/philomena_web/templates/admin/badge/user/index.html.slime
- lib/philomena_web/templates/admin/dnp_entry/index.html.slime
- lib/philomena_web/templates/admin/donation/index.html.slime
- lib/philomena_web/templates/admin/fingerprint_ban/index.html.slime
- lib/philomena_web/templates/admin/mod_note/index.html.slime
- lib/philomena_web/templates/admin/report/index.html.slime
- lib/philomena_web/templates/admin/site_notice/index.html.slime
- lib/philomena_web/templates/admin/subnet_ban/index.html.slime
- lib/philomena_web/templates/admin/user/index.html.slime
- lib/philomena_web/templates/admin/user_ban/index.html.slime
- lib/philomena_web/templates/moderation_log/index.html.slime
- lib/philomena_web/templates/notification/category/show.html.slime
- lib/philomena_web/templates/source_change/index.html.slime
- lib/philomena_web/templates/tag_change/index.html.slime
> Small frontend changes regarding pagination

- assets/css/views/tags.css
- lib/philomena_web/templates/tag/_tag.html.slime
> Add icons to tag dropdowns

- lib/philomena_web/templates/image/related/index.html.slime
Similar to other pages like tag changes
> Add link to image on related page

- lib/philomena/comments.ex
- lib/philomena/images.ex
- lib/philomena/tag_changes.ex
- lib/philomena_web/controllers/image/tag_controller.ex
> Fix missing reindexes

- lib/philomena_web/templates/profile/show.html.slime
> Add a confirm prompt when rejecting an artist link on profile

- assets/css/views/images.css
> fix multiple image sources being not visible on safari 17.6

- scripts/philomena.sh
This is a cherry-pick from #528
> Add `--drop-cache`, `compose` and `exec` commands to `philomena.sh`

- lib/philomena_web/templates/tag/_tag_info_row.html.slime
> Sort implied-by tag list

- lib/philomena/users/ability.ex
> Allow mods to :show all posts

- lib/philomena_proxy/scrapers/civitai.ex
---
https://github.com/philomena-dev/philomena/pull/614#issuecomment-3092460042
> Now grabbing original images from Civitai

- lib/philomena_web/templates/admin/artist_link/index.html.slime
- lib/philomena_web/templates/admin/dnp_entry/index.html.slime
- lib/philomena_web/templates/admin/fingerprint_ban/index.html.slime
- lib/philomena_web/templates/admin/report/index.html.slime
- lib/philomena_web/templates/admin/subnet_ban/index.html.slime
- lib/philomena_web/templates/admin/user/index.html.slime
- lib/philomena_web/templates/admin/user_ban/index.html.slime
- lib/philomena_web/templates/channel/_form.html.slime
- lib/philomena_web/templates/channel/index.html.slime
- lib/philomena_web/templates/comment/index.html.slime
- lib/philomena_web/templates/filter/_form.html.slime
- lib/philomena_web/templates/filter/index.html.slime
- lib/philomena_web/templates/layout/_header.html.slime
- lib/philomena_web/templates/post/index.html.slime
- lib/philomena_web/templates/profile/artist_link/_form.html.slime
- lib/philomena_web/templates/search/_form.html.slime
- lib/philomena_web/templates/setting/edit.html.slime
- lib/philomena_web/templates/tag/_tag_editor.html.slime
- lib/philomena_web/templates/tag/index.html.slime
Some browsers (Safari) are too intrusive with spellcheck which makes it annoying
> Disable spellcheck on a bunch of text inputs

- assets/js/__tests__/preview.spec.ts
- assets/js/image_expansion.js
- assets/js/preview.ts
The test is AI-generated. Seems to work.
> Convert preview.js to Typescript
